extends: ['./.eslintrc.yml', 'plugin:@typescript-eslint/eslint-recommended']
parser: '@typescript-eslint/parser'
plugins: ["@typescript-eslint"]
rules:
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-use-before-define': 'off'
  'no-unused-vars': "off"
  '@typescript-eslint/no-unused-vars': ["error"]
