env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

rules:
  react/react-in-jsx-scope: 0

globals:
  React: true
  propTypes: true
  renderer: true
  shallow: true
  mount: true

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'
