const ActionType = {
  LOAD_FILM_DETAIL_REQUEST: `LOAD_FILM_DETAIL_REQUEST`,
  LOAD_FILM_DETAIL_SUCCESS: `LOAD_PROMO_FILM_SUCCESS`,
  LOAD_FILM_DETAIL_ERROR: `LOAD_FILM_DETAIL_ERROR`
};

export default ActionType;
