const ActionType = {
  LOAD_PROMO_FILM_REQUEST: `LOAD_PROMO_FILM_LOADING`,
  LOAD_PROMO_FILM_SUCCESS: `LOAD_PROMO_FILM_SUCCESS`,
  LOAD_PROMO_FILM_ERROR: `LOAD_PROMO_FILM_ERROR`,
};

export default ActionType;
